### ISSUE TITLE
Ruby Group Capstone

### ISSUE THREAD

**Issue by iLynette** [iLynette/catalog_of_things#29]
[Project Link](https://github.com/iLynette/catalog_of_things/projects/1)

We are a team of three;

- Team member 1: @iLynette 
- Team member 2: @daudi13 
- Team member 3: @Tufahel

**Comment by Tufahel** [comment]
Thank you @Lordkaito for your review. We have worked on your suggestions by adding descriptions to all tasks and adjusting task points.

**Comment by Mihndim2020** [comment]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi Team, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by iLynette** [comment]
Thank you @Mihndim2020 😉
